on:
  pull_request:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: testando github actions
        run: echo Hello World