on:
  pull_request:
    branches: [main]

env:
  CMS_API_TOKEN: ${{ secrets.CMS_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run installation
        run: npm install
      - name: Run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run installation
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run deploy
        run: npm run netlify deploy --auth ${{ secrets.NETLIFY_TOKEN }}
